# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: ci
      run: make ci

    - name: build_release
      run: make VERSION=${GITHUB_REF_NAME} release -j3
      if: github.ref_type == 'tag'

    - name: publish
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: 'release/*'
